### PR TITLE
At least the circleCi works? 

### PR DESCRIPTION
**Pull request by nabobalis**
Since CircleCi and Giles is not setup here yet.

You can see the builds for this PR here: https://circleci.com/gh/nabobalis/sunpy-1.0-paper

The latest pdf build: https://circleci.com/gh/nabobalis/sunpy-1.0-paper/5/artifacts/0//root/project/main.pdf 

TODO:
- [ ] Check references are created

### CODE REVIEW

**Comment by nabobalis** [comment]
List of things I did:

1. The class file was different to the one from the main website (added the bib style file for good measure)
2. Added the missing commands to the main.tex
3. Added the figures missing from the repo that were on the overleaf build.

**Comment by nabobalis** [comment]
We might want to check if any other text was not transferred over?

**Comment by mbobra** [comment]
It looks like the references to cited papers and the references to other sections didn't turn up correctly -- although the fix may be as simple as running it twice. Is BibTeX processing the `bibliography.bib` file?

**Comment by nabobalis** [comment]
So moving to latexmk (it runs the correct number of pdflatex and bibtex automatically for you) has reported a bunch of bibtex errors (probably to do with the style file I added, woops):

https://circleci.com/gh/nabobalis/sunpy-1.0-paper/8

Unfortunately I am unable to fix this until I get home from work in about ~9 hours.

**Comment by Cadair** [comment]
I turned on circle eventually :roll_eyes:

**Comment by nabobalis** [comment]
What was the fix?

**Comment by Cadair** [comment]
@nabobalis use chromium and prod it from within the dev tools

**Review by Cadair — APPROVED** [review]

**Pull request merged**
