### PR TITLE
Edits after thorough read through

### LINKED ISSUE #87: Add a paragraph to section 7 to discuss other components of sunpy.net
This means putting back in the reference to helioviewer that was deleted as well as other things.

### PR DESCRIPTION
**Pull request by wtbarnes**
**This PR is ready for review.**

This PR consists of edits throughout the text of the paper, including some reorganizing of the sections. I've summarized the major changes below.

I've isolated changes to each section to their own commit so this can be broken up if need be.

Also fixes #87 

## Major Changes

* Moved the "Community" section from section 10 to section 5 (just after the "Development Model" section)
* Removed the last paragraph of the "Community" section as it repeated what was already said in section 4
* **Put all code-related discussion (data retrieval, data types, coordinates, units) into its own section called "The SunPy Core Package". Each of those sections is now a subsection.**
* Breakup "Data Search and Retrieval" section into 3 subsection (Fido, HEK, Helioviewer) to emphasize other components of `sunpy.net` besides `Fido`.
* Removed "Differential Rotation" section, including the figure.
* Shortened intro to "Units and Time Scales" section and moved info about Mars Climate Orbiter to a footnote

### CODE REVIEW

**Comment by wtbarnes** [comment]
## Major Changes

* Moved the "Community" section from section 10 to section 5 (just after the "Development Model" section)
* Removed the last paragraph of the "Community" section as it repeated what was already said in section 4

**Comment by ayshih** [comment]
> * Removed "Differential Rotation" section, including the figure.

I'm not particularly attached to this section/figure, but has there been broad agreement to removing it?

**Comment by wtbarnes** [comment]
@ayshih I'm not sure, but perhaps we can have that discussion on this PR or during the telecon on Wednesday. 

I'm happy to add it back in if people really want it, or if there are suggestions about how to better integrate it into an existing section.

I removed it because it doesn't really make sense for it to have its own section and it does not fit in the coordinates section either.

**Comment by ehsteve** [comment]
I'm not a big fan or removing the differential rotation section and figure either.

**Comment by wtbarnes** [comment]
> I'm not a big fan or removing the differential rotation section and figure either.

Do you have a suggestion of where it should go? It seems strange to give it its own section, but it also does not really fit in the coordinates section. If the consensus is to leave it as is in its own section under coordinates, that's fine, but it just seems a bit awkward.

**Comment by nabobalis** [comment]
Closed in favour of #115 as it has all of the commits.

**Pull request closed without merging**
