### PR TITLE
Restructure introduction

### PR DESCRIPTION
**Pull request by wtbarnes**
This PR is the result of work between myself and @mbobra. It restructures the introduction with a heavier focus on the strengths of Python and the scientific Python ecosystem. 

@mbobra I ended up not including the bits about the benefits of open development because it seemed to make it a bit to long and I couldn't figure out how to fit it in. If you have an idea of how to work it in, please do!

### CODE REVIEW

**Comment by ehsteve** [comment]
I think this reads pretty well though I think that it is important that this be written and targeted specifically to solar. Your edit removed all of that. Right now this section would be equally applicable to biology or geology. The key points that I had in my text was about the size of the solar community, which is small, and therefore gains significantly more leverage by using already developed tools. As well as to remind readers about the past transition from Fortran to IDL. It's true that that section was probably long. 

You could argue that my solar-specific points were not strong enough and I'd be happy to discuss other points but the key is that this has to be specific to our community and not generic.

**Comment by wtbarnes** [comment]
Fair point. I've added the Fortran/IDL discussion back in and adapted my changes appropriately. Let me know what you think. Reading it through, I don't actually think the length is really an issue.

**Review by ehsteve — APPROVED** [review]

**Comment by mbobra** [comment]
I think this is well-written and motivated -- thanks for working on this, @wtbarnes.

I personally do not think that a history about the transition from Fortran to IDL and then IDL to Python is relevant here for a few reasons:

- I think the SunPy Project has more to offer than just scientific Python -- we offer the opportunity to create a _community-developed_ and _version-controlled_ scientific software package, which, as @wtbarnes pointed out to me on Friday, is theoretically possible with IDL. 
- I do not think we are trying to replace IDL with Python. It is these kinds of statements that lead the outside community to assume SunPy will be a direct replacement for SSW. This can also be easily misconstrued as IDL-bashing, which we in the PyAstro community need to be careful to avoid. 
- Neither the [AstroPy+2013](https://doi.org/10.1051/0004-6361/201322068) paper or the [AstroPy+2018](https://doi.org/10.3847/1538-3881/aabc4f) paper mentioned IDL at all, even though it is popular in the astrophysics community -- according to [Momcheva+2015](https://arxiv.org/abs/1507.03989), ~40% of the astrophysics community used IDL in 2015. (It looks like IDL wasn't even mentioned in any of the issues or PRs to [the AstroPy+2018 repo](https://github.com/astropy/astropy-v2.0-paper)). I know AstroPy's decisions aren't universally relevant to SunPy, but my guess is that they did not mention IDL for the same reasons I outlined above.

As for @ehsteve's comment:

> The key points that I had in my text was about the size of the solar community, which is small, and therefore gains significantly more leverage by using already developed tools.

It looks like @wtbarnes still has that information in the text:

> Because the solar community is relatively small\footnote{For reference, out of the $\sim$9,500 members of the American Astronomy Society, approximately 500 are members of the society's Solar Physics Division.} in relation to other scientific communities, it stands to benefit immensely by utilizing the \python scientific stack to solve increasingly difficult scientific challenges and produce world-class science.

**Comment by wtbarnes** [comment]
Regarding the last point about the size of the solar community, I added that back in following @ehsteve's review. I had initially removed it, but I think it fits in well with the discussion of the scipy ecosystem.

**Pull request merged**
