### PR TITLE
Various fixes to figures

### PR DESCRIPTION
**Pull request by ehsteve**
- [x] issue #88, #98, #90
- [x] address issue #89 

This depends on PR #96.

### CODE REVIEW

**Comment by ehsteve** [comment]
@ayshih predicted position of Venus is still off by a few arcsec. See the new plot.

**Comment by ehsteve** [comment]
I realize I made a mistake in the Venus angular extent calculation. Will fix soon.

**Comment by ayshih** [comment]
> @ayshih predicted position of Venus is still off by a few arcsec. See the new plot.

The AIA file you download is a Level 1.0 file.  If you run it through SSW's `aia_prep` – not SunPy's facsimile –  to get to Level 1.5, this is the plot you get, which looks much better (although still slightly off):
Figure_1
That is, SSW's `aia_prep` uses pointing information to correct for ~8 arcmin of roll misalignment.

**Comment by ayshih** [comment]
Actually, if I use `get_horizons_coord()` to get the SDO spacecraft position (different from the header position by 47 km), plus a minor bug fix for `get_horizons_coord()`, the agreement is even better:
Figure_2

Either way, the discrepancy is <~0.5 arcseconds.

**Comment by ehsteve** [comment]
Well that’s annoying that you need aiaprep. Since you now have the prepped image could you PR the prepped fits file to the repo please @ayshih?

**Comment by ayshih** [comment]
Done (#101)

**Comment by ayshih** [comment]
> Well that’s annoying that you need aiaprep.

Did some poking around, and the problem was specific to the file you were working with: it has out-of-date pointing information in its header.  (In fact, it might be the case that this incorrect header reflects the state of knowledge prior to analysis of the Venus-transit data!)  SSW's `aia_prep` ignores the pointing information in the header by default and instead accesses up-to-date pointing information.  I just now grabbed the same exposure off of VSO, and the header provided has the up-to-date pointing information.

**Pull request merged**
