### PR TITLE
Adding acknowledgement section

### PR DESCRIPTION
**Pull request by bsipocz**
I took the structure of the acknowledgement section from the astropy paper where we had a generic section to thank everyone (and maintainers who didn't want to be co-authors), then companies and institutions from where funding came in some form and then individual grant acknowledgements.

Please revise as you see best, as well fill in the central part as I don't know exactly how many students you had over the years from various sources, neither know about any other direct funding.

### CODE REVIEW

**Comment by mbobra** [comment]
@bsipocz It looks like acknowledgements is misspelled in the file name (`acknowledgments.tex`), so the line `\input{sections/acknowledgements.tex}` fails to find the file. Do you mind fixing this mismatch?

**Comment by bsipocz** [comment]
Done, that was indeed a stupid misspell.

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
Thanks @bsipocz

**Comment by ehsteve** [comment]
Any issues with this being included? I don’t have any myself and I suggest anyone want sit add this kind of acknowledgement to do so as well.

**Comment by bsipocz** [comment]
Note: this PR had a placeholder TODO for more details stuff about GSoC, SOCIS, NumFOCUS, etc places from where more direct funding came. Someone familiar with those details should expand. @Cadair or @dpshelio perhaps?

**Pull request merged**
