### PR TITLE
Fixes to the meta plots

### PR DESCRIPTION
**Pull request by ehsteve**

### CODE REVIEW

**Comment by nabobalis** [comment]
Seems that we need to rename the figure file name:

```
Package pdftex.def Error: File `figures/fig_venus_transit_1600_20120606_04072
9.pdf' not found: using draft setting.
```

**Comment by nabobalis** [comment]
Also does this update the figure 1a?

**Comment by ehsteve** [comment]
yes and yes

**Comment by nabobalis** [comment]
Thanks, I will then update the caption and I might play around with the first figure.

**Comment by ehsteve** [comment]
@nabobalis sorry I spoke too soon.

**Comment by ehsteve** [comment]
@nabobalis having trouble updating that plot. I'll probably have to work on it over the weekend. I'll create an issue to fix it so that this can go in.

**Comment by nabobalis** [comment]
Thats fine!

**Pull request merged**
