### PR TITLE
Minor edits

### PR DESCRIPTION
**Pull request by wafels**
Some minor edits to the text

### CODE REVIEW

**Comment by nabobalis** [comment]
Add yourself as an author!

**Comment by wafels** [comment]
I think I am added???

**Comment by nabobalis** [comment]
You just opened the issue?

**Comment by ayshih** [comment]
It's my fault on the GitHub spacing.  Please remove your patched-in spaces, and change the macro in `main.tex` to the below:
```
\newcommand{\github}{GitHub\xspace}
```

**Review by ehsteve — APPROVED** [review]

**Comment by ehsteve** [comment]
I'll take over and will fix this @ayshih @wafels.

**Pull request merged**
